// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq3grR6Rms6TjCCTpLGqbzddqhCmscTc8',
    appId: '1:29226662401:web:5f7aaa187b440b47cbde00',
    messagingSenderId: '29226662401',
    projectId: 'mobile-project-43ec4',
    authDomain: 'mobile-project-43ec4.firebaseapp.com',
    storageBucket: 'mobile-project-43ec4.firebasestorage.app',
    measurementId: 'G-9YM8H8WSYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBijivpRjS4irRQnnZN77TgYNRqk_BV8r4',
    appId: '1:29226662401:android:ce60611e40aaceb2cbde00',
    messagingSenderId: '29226662401',
    projectId: 'mobile-project-43ec4',
    storageBucket: 'mobile-project-43ec4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdZVNwzvn0K5xzuNpcmVeX-WSTelhhZEA',
    appId: '1:29226662401:ios:e96f03d7b2a01656cbde00',
    messagingSenderId: '29226662401',
    projectId: 'mobile-project-43ec4',
    storageBucket: 'mobile-project-43ec4.firebasestorage.app',
    iosBundleId: 'com.example.mobileProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdZVNwzvn0K5xzuNpcmVeX-WSTelhhZEA',
    appId: '1:29226662401:ios:e96f03d7b2a01656cbde00',
    messagingSenderId: '29226662401',
    projectId: 'mobile-project-43ec4',
    storageBucket: 'mobile-project-43ec4.firebasestorage.app',
    iosBundleId: 'com.example.mobileProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq3grR6Rms6TjCCTpLGqbzddqhCmscTc8',
    appId: '1:29226662401:web:8639976c66a485d5cbde00',
    messagingSenderId: '29226662401',
    projectId: 'mobile-project-43ec4',
    authDomain: 'mobile-project-43ec4.firebaseapp.com',
    storageBucket: 'mobile-project-43ec4.firebasestorage.app',
    measurementId: 'G-VFMD8JTCPT',
  );
}
